# Generated by Django 5.2.3 on 2025-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_vlogpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogpost',
            name='is_article',
            field=models.BooleanField(default=False),
        ),
    ]
