# Generated by Django 5.2.3 on 2025-07-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VlogPost',
        ),
    ]
