# Generated by Django 5.1.1 on 2025-07-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogpost',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
