# Generated by Django 5.2.3 on 2025-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
