# Generated by Django 5.1.1 on 2025-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_quote_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
