# Generated by Django 5.1.1 on 2025-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_vlogpost_image_vlogpost_image_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
